# Generated by Django 3.2.15 on 2022-10-06 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=255)),
                ('categoryImage', models.ImageField(upload_to='Ecomm_images')),
                ('mainCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acount.maincategory')),
                ('subCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acount.subcategory')),
            ],
            options={
                'db_table': 'ChildCategory',
            },
        ),
    ]
