# Generated by Django 3.2.15 on 2022-10-10 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acount', '0004_alter_maincategory_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcategory',
            name='description',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('productImage', models.ImageField(upload_to='EcommProductImages')),
                ('description', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('childCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acount.childcategory')),
                ('mainCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acount.maincategory')),
                ('subCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acount.subcategory')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
