# Generated by Django 3.2.15 on 2022-10-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acount', '0005_auto_20221010_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='childCategory',
            new_name='childCategoryId',
        ),
    ]
