# Generated by Django 3.2.15 on 2022-10-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount', '0007_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planName', models.CharField(max_length=255)),
                ('planValue', models.IntegerField()),
                ('statusText', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Plan',
            },
        ),
    ]
