# Generated by Django 3.2.15 on 2022-10-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount', '0008_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobileNo', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
    ]
